### ISSUE TITLE
TypeError: None has type NoneType, but expected one of: int, long

### ISSUE THREAD

**Issue by CSutter5** [Bengemon825/TF_Object_Detection2020#2]
When I run ```python generate_tfrecord.py --csv_input=data/test_labels.csv --output_path=data/test.record --image_dir=images/test/```  I get
```Traceback (most recent call last):
  File "generate_tfrecord.py", line 104, in <module>
    tf.app.run()
  File "E:\Miniconda\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Colin\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\Colin\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 95, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 84, in create_tf_example
    'image/object/class/label': dataset_util.int64_list_feature(classes),
  File "E:\Miniconda\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\utils\dataset_util.py", line 30, in int64_list_feature
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))
TypeError: None has type NoneType, but expected one of: int, long
```
As an output

I have change the pbtxt file and the generate_tfrecord file with my object and the id

**Comment by CSutter5** [comment]
Found fix don't return none return 0

Pull request https://github.com/Bengemon825/TF_Object_Detection2020/pull/3
