### ISSUE TITLE
StringIntLabaelMapItem has no field frequency

### ISSUE THREAD

**Issue by mlopez0** [Bengemon825/TF_Object_Detection2020#6]
Hi, I was able to follow the whole Tutorial, solving some minor issues found during the road, however in the last step:

`python3 webcam_detection.py 
`

 to test the model with the webcam I got this error:

```
Traceback (most recent call last):
  File "webcam_detection.py", line 76, in <module>
    categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
  File "/home/marvin/Desktop/models/research/object_detection/utils/label_map_util.py", line 133, in convert_label_map_to_categories
    if item.HasField('frequency'):
ValueError: Protocol message StringIntLabelMapItem has no field frequency.


```

**Comment by Petros626** [comment]
Hell yeah I have the same error, but decided to let it be for the next steps including the training it doesn't matter, but it's still unsatisfying
